services:
  server:
    image: ghcr.io/h5misi/nodejs-image:1.0
    expose:
      - "3000"
    command: ["node", "server.js"]
    networks:
      - internal


  nginx:
    image: nginx:1.30
    networks:
      - internal
      - caddy-ingress
    labels:
      caddy: nodeapp.dev1.mnt.group
      caddy.reverse_proxy: "{{upstreams 80}}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/usr/share/nginx/html:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro

networks:
  internal:
  caddy-ingress:
    external: true