services:
  server:
    image: node:24-bookworm
    working_dir: /server
    volumes:
      - .:/server
    expose:
      - "3000"
    command: ["node", "server.js"]


  nginx:
    image: nginx:1.30
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/usr/share/nginx/html:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro