name: CI/CD

on:
  push:
    branches:
      - testing

jobs:
  build-and-test:
  # ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  deploy:
  # cd
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        run: |
          ssh meow@dev1.mnt.group '
            cd /home/meow/hazem/nodejs-hosting-server &&
            git pull &&
            docker compose -f docker-compose-prod.yml up -d
          '