name: CI/CD

on:
  push:
    branches:
      - testing

jobs:
  build-and-test:
    # CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build-and-push-image:
    # Build Docker image and publish it to GHCR
    needs: build-and-test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/h5misi/nodejs-image:1.0 \
            .

      - name: Push Docker image
        run: |
          docker push ghcr.io/h5misi/nodejs-image:1.0

  deploy:
    # CD
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H dev1.mnt.group >> ~/.ssh/known_hosts

      - name: Prepare deployment directories
        run: |
          ssh -i ~/.ssh/github_actions meow@dev1.mnt.group '
            mkdir -p /home/meow/hazem/nodejs-hosting-server/nginx
          '

      - name: Copy deployment files to server
        run: |
          scp -i ~/.ssh/github_actions \
            docker-compose-prod.yaml \
            meow@dev1.mnt.group:/home/meow/hazem/nodejs-hosting-server/

          scp -i ~/.ssh/github_actions \
            nginx/nginx.conf \
            meow@dev1.mnt.group:/home/meow/hazem/nodejs-hosting-server/nginx/

          scp -i ~/.ssh/github_actions \
            nginx/.htpasswd \
            meow@dev1.mnt.group:/home/meow/hazem/nodejs-hosting-server/nginx/

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/github_actions meow@dev1.mnt.group '
            cd /home/meow/hazem/nodejs-hosting-server &&
            docker compose -f docker-compose-prod.yaml pull &&
            docker compose -f docker-compose-prod.yaml up -d
          '